kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: l3cni-two-node
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/bpf-map-control/
    containerPath: /tmp/bpf-map/
    propagation: Bidirectional
    selinuxRelabel: false
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.240.0.0/16"