#!/bin/bash
log="/var/log/cni.log"
config=$(cat /dev/stdin)

echo "config: $config" >> "$log"
echo "COMMAND: $CNI_COMMAND" >> "$log"
echo "env: $(printenv)" >> "$log"

if [ "$CNI_COMMAND" == "ADD" ]; then
    podcidr=$(echo $config | jq -r ".podcidr")
    peer_net=$(echo $config | jq -r ".peer_net")
    peer_ip=$(echo $config | jq -r ".peer_ip")
    netns_name=$(echo "$CNI_NETNS" | cut -d'/' -f5)


    file="/tmp/host"
    if [ ! -f "$file" ]; then
        echo 2 > "$file"
        host=2

    else
        host=$(<"$file")
        ((host++))
        echo "$host" > "$file"
    fi

    pod_cidr=$(echo "$podcidr" | sed "s:\.0/24:.$host:")/32
    host_nic=host-"$host"
    host_nic_ip=$(echo "$podcidr" | sed "s:\.0/24:.1:")
    host_nic_cidr=$host_nic_ip/32

    ip link add "$host_nic" type veth peer name $CNI_IFNAME netns $netns_name

    ip netns exec $netns_name ip link set $CNI_IFNAME up
    ip link set "$host_nic" up

    ip netns exec "$netns_name" ip addr add "$pod_cidr" dev $CNI_IFNAME
    ip addr add "$host_nic_cidr" dev $host_nic

    ip netns exec "$netns_name" ip route add $host_nic_ip dev $CNI_IFNAME
    ip netns exec "$netns_name" ip route add default via $host_nic_ip dev $CNI_IFNAME
    ip route add "$pod_cidr" dev "$host_nic"
    ip route add "$peer_net" via "$peer_ip" dev eth0


    output_template='
    {
      "cniVersion": "0.3.1",
      "interfaces": [
          {
              "name": "%s",
              "mac": "%s",
              "sandbox": "%s"
          }
      ],
      "ips": [
          {
              "version": "4",
              "address": "%s",
              "interface": 0
          }
      ]
    }'

    pod_mac=$(ip link show "$CNI_IFNAME" | awk '/link\/ether/ {print $2}')
    output=$(printf "${output_template}" "$CNI_IFNAME" "$pod_mac" "$CNI_NETNS" "$pod_cidr")
    echo "$output" >> "$log"
    echo "$output"

elif [ "$CNI_COMMAND" == "DEL" ]; then
    # Handle DEL command
    echo "DEL command"
elif [ "$CNI_COMMAND" == "VERSION" ]; then
    echo '{
      "cniVersion": "0.3.1",
      "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ]
    }'
else
    echo "Unknown cni command: $CNI_COMMAND"
    exit 1
fi
